/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AniDashAniDashImport } from './routes/ani-dash/AniDash'
import { Route as AniDashAniCompleteImport } from './routes/ani-dash/AniComplete'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AniDashAniDashRoute = AniDashAniDashImport.update({
  id: '/ani-dash/AniDash',
  path: '/ani-dash/AniDash',
  getParentRoute: () => rootRoute,
} as any)

const AniDashAniCompleteRoute = AniDashAniCompleteImport.update({
  id: '/ani-dash/AniComplete',
  path: '/ani-dash/AniComplete',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ani-dash/AniComplete': {
      id: '/ani-dash/AniComplete'
      path: '/ani-dash/AniComplete'
      fullPath: '/ani-dash/AniComplete'
      preLoaderRoute: typeof AniDashAniCompleteImport
      parentRoute: typeof rootRoute
    }
    '/ani-dash/AniDash': {
      id: '/ani-dash/AniDash'
      path: '/ani-dash/AniDash'
      fullPath: '/ani-dash/AniDash'
      preLoaderRoute: typeof AniDashAniDashImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ani-dash/AniComplete': typeof AniDashAniCompleteRoute
  '/ani-dash/AniDash': typeof AniDashAniDashRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ani-dash/AniComplete': typeof AniDashAniCompleteRoute
  '/ani-dash/AniDash': typeof AniDashAniDashRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ani-dash/AniComplete': typeof AniDashAniCompleteRoute
  '/ani-dash/AniDash': typeof AniDashAniDashRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ani-dash/AniComplete' | '/ani-dash/AniDash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ani-dash/AniComplete' | '/ani-dash/AniDash'
  id: '__root__' | '/' | '/ani-dash/AniComplete' | '/ani-dash/AniDash'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AniDashAniCompleteRoute: typeof AniDashAniCompleteRoute
  AniDashAniDashRoute: typeof AniDashAniDashRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AniDashAniCompleteRoute: AniDashAniCompleteRoute,
  AniDashAniDashRoute: AniDashAniDashRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ani-dash/AniComplete",
        "/ani-dash/AniDash"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ani-dash/AniComplete": {
      "filePath": "ani-dash/AniComplete.tsx"
    },
    "/ani-dash/AniDash": {
      "filePath": "ani-dash/AniDash.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
