/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AniDashImport } from './routes/AniDash'
import { Route as AniCompleteImport } from './routes/AniComplete'

// Create/Update Routes

const AniDashRoute = AniDashImport.update({
  id: '/AniDash',
  path: '/AniDash',
  getParentRoute: () => rootRoute,
} as any)

const AniCompleteRoute = AniCompleteImport.update({
  id: '/AniComplete',
  path: '/AniComplete',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/AniComplete': {
      id: '/AniComplete'
      path: '/AniComplete'
      fullPath: '/AniComplete'
      preLoaderRoute: typeof AniCompleteImport
      parentRoute: typeof rootRoute
    }
    '/AniDash': {
      id: '/AniDash'
      path: '/AniDash'
      fullPath: '/AniDash'
      preLoaderRoute: typeof AniDashImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/AniComplete': typeof AniCompleteRoute
  '/AniDash': typeof AniDashRoute
}

export interface FileRoutesByTo {
  '/AniComplete': typeof AniCompleteRoute
  '/AniDash': typeof AniDashRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/AniComplete': typeof AniCompleteRoute
  '/AniDash': typeof AniDashRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/AniComplete' | '/AniDash'
  fileRoutesByTo: FileRoutesByTo
  to: '/AniComplete' | '/AniDash'
  id: '__root__' | '/AniComplete' | '/AniDash'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AniCompleteRoute: typeof AniCompleteRoute
  AniDashRoute: typeof AniDashRoute
}

const rootRouteChildren: RootRouteChildren = {
  AniCompleteRoute: AniCompleteRoute,
  AniDashRoute: AniDashRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/AniComplete",
        "/AniDash"
      ]
    },
    "/AniComplete": {
      "filePath": "AniComplete.tsx"
    },
    "/AniDash": {
      "filePath": "AniDash.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
